name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - streamlit=1.38
  - pandas
  - numpy=2.0
  - beautifulsoup4
  - matplotlib
  - requests
  - pip
  - pip:
    - streamlit_lottie
    - st_pages

