[[pages]]
path = "home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "p_test.py"
name = "Personality Test"
icon = "ğŸ“"

[[pages]]
path = "p_types.py"
name = "Personality Types"
icon = "ğŸ’–"

[[pages]]
path = "about.py"
name = "About"
icon = "â„¹ï¸"

