[[pages]]
path = "./home/home.py"
name = "HOME"
icon = "ğŸ "

[[pages]]
name = "Understand Your Personality!"
icon = "ğŸ«µ"
is_section = true

[[pages]]
path = "./p_test/p_test.py"
name = "PERSONALITY TEST"
icon = "ğŸ“"

[[pages]]
path = "./p_types/p_types.py"
name = "PERSONALITY TYPES"
icon = "ğŸ’–"

[[pages]]
name = "Contact Us"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "./about/about.py"
name = "ABOUT"
icon = "â„¹ï¸"

